### ISSUE TITLE
missing gems in Gemfile

### ISSUE THREAD

**Issue by EricDeveaud** [ProbstLab/uBin-helperscripts#1]
Hello 

in order to be abble to run the Helper scripts I had to manually install some gems that are not listed on Gemgfile

```
    gem install ox -v 2.5.0
    gem install trollop -v 2.1.2
    gem install moneta -v 1.2.0
```

regards

Eric

**Comment by ProbstLab** [comment]
Hi Erik, 

Sorry for the super late reply! I (Till) missed setting notifications to my personal GitHub account and thus completely missed this notification. The gems were added to the gemfile. 

Thanks for pointing them out!

Best,
Till
