### ISSUE TITLE
scaffold must be in pwd

### ISSUE THREAD

**Issue by EricDeveaud** [ProbstLab/uBin-helperscripts#2]
target scaffold must be in pwd 
if not there is an erro in 04_00map_mod.sh that cannot create bowtie index directory

as the error is not tracked (you may want to check return values of the executed commands) 
that produce later to some other errors 

see:

```
Singularity> uBin_wrapper.sh -s example_dataset/scaffolds.fasta -p pdbg -r1 example_dataset/BG_1_S1_L001_interleaved_trim_clean.PE.1.fastq.gz -r2 example_dataset/BG_1_S1_L001_interleaved_trim_clean.PE.2.fastq.gz -e diamond -t 10 -b example_dataset/das_tool_DASTool_scaffolds2bin.txt
all files will get generated from scratch
creating mapping index
/usr/local/bin/04_00map_mod.sh: line 16: bt2/example_dataset/scaffolds.fasta.log: No such file or directory
mapping...

SNIP // SNAP 

parsing length of each scaffold...
cleaning up...
...done!

Error:  no input sequences to analyze.   

SNIP /above error repeated 44 x/ SNAP 

diamond v0.9.14.115 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

SNIP // SNAP

Reported 11777 pairwise alignments, 11778 HSPs.
11777 queries aligned.
pdbg_min1000.genes.faa.bacteria.scg pdbg_min1000.genes.faa.archaea.scg
running blast for bacterial SCGs... this may take a while...
SCG prediction worked
```

but sadly `uBin_wrapper.sh` will continue and finaly exit 0 that means usualy succes.
I'm not sure we can call this success ? 

regards 

Eric

**Comment by ProbstLab** [comment]
Hi Eric,

I've for now edited the README to say that the script should be executed from the folder with the assembly file and will see about adding in some checks to check for the individual files being generated and if not, to return an error.

Best,
Till

**Comment by till-bornemann** [comment]
Hi Eric, 
I modified the mapping subscripts to no longer rely on the scaffolds file to be in the current folder. The README has also been adjusted accordingly. 

Best,
Till
